### ISSUE TITLE
Elasticsearch refuses to start with a named volume on Docker for Mac

### ISSUE THREAD

**Issue by ndegory** [appcelerator-archive/amp#1321]
Our custom elasticsearch image refuses to start on Docker for Mac when a volume is mounted on the data folder.
Related to elastic/elasticsearch-docker#44, issue with openjdk and Alpine's musl lib

Upgrading to Alpine 3.6 should fix it.

```
amp_elasticsearch.1.vmvb0n5qz6sk@moby    | INFO - system memory is 2046M
amp_elasticsearch.1.vmvb0n5qz6sk@moby    | INFO - set java heap size to ramping value
amp_elasticsearch.1.vmvb0n5qz6sk@moby    | Java Heap Size: 309 MB
amp_elasticsearch.1.vmvb0n5qz6sk@moby    | memory lock limit:
amp_elasticsearch.1.vmvb0n5qz6sk@moby    | 82000
amp_elasticsearch.1.vmvb0n5qz6sk@moby    | 82000
amp_elasticsearch.1.vmvb0n5qz6sk@moby    | Hard limit max open fd:1048576
amp_elasticsearch.1.vmvb0n5qz6sk@moby    | Max open fd:1048576
amp_elasticsearch.1.vmvb0n5qz6sk@moby    | resolving the container IP with Docker DNS...
amp_elasticsearch.1.vmvb0n5qz6sk@moby    | this node ip is 10.0.0.5
amp_elasticsearch.1.vmvb0n5qz6sk@moby    | INFO - setting user perms on elasticsearch data dir
amp_elasticsearch.1.vmvb0n5qz6sk@moby    | INFO - running elasticsearch as user elastico
amp_elasticsearch.1.vmvb0n5qz6sk@moby    | INFO - running gosu elastico elasticsearch
amp_elasticsearch.1.vmvb0n5qz6sk@moby    | [2017-06-05T17:40:47,040][INFO ][o.e.n.Node               ] [] initializing ...
amp_elasticsearch.1.vmvb0n5qz6sk@moby    | [2017-06-05T17:40:47,101][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
amp_elasticsearch.1.vmvb0n5qz6sk@moby    | org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: failed to obtain node locks, tried [[/opt/elasticsearch/data/elasticsearch]] with lock id [0]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [1])?
amp_elasticsearch.1.vmvb0n5qz6sk@moby    | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:127) ~[elasticsearch-5.4.0.jar:5.4.0]
amp_elasticsearch.1.vmvb0n5qz6sk@moby    | 	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) ~[elasticsearch-5.4.0.jar:5.4.0]
amp_elasticsearch.1.vmvb0n5qz6sk@moby    | 	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67) ~[elasticsearch-5.4.0.jar:5.4.0]
amp_elasticsearch.1.vmvb0n5qz6sk@moby    | 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.4.0.jar:5.4.0]
amp_elasticsearch.1.vmvb0n5qz6sk@moby    | 	at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.4.0.jar:5.4.0]
amp_elasticsearch.1.vmvb0n5qz6sk@moby    | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.4.0.jar:5.4.0]
amp_elasticsearch.1.vmvb0n5qz6sk@moby    | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.4.0.jar:5.4.0]
amp_elasticsearch.1.vmvb0n5qz6sk@moby    | Caused by: java.lang.IllegalStateException: failed to obtain node locks, tried [[/opt/elasticsearch/data/elasticsearch]] with lock id [0]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [1])?
```

**Comment by vinayak12** [comment]
@ndegory  i am seeing this issue on mac with image docker.elastic.co/elasticsearch/elasticsearch:5.4.0.
Elasticserach is on centos. How will Alpine  3.6 fix it. Are you taking about docker for mac  internal OS ? If yes, how we can update the docker for mac Apline OS ?

**Comment by ndegory** [comment]
@vinayak12 it's supposed to be fixed in the upstream image, either with the package updates (musllib and openjdk), or with Alpine 3.6 that includes these fixes. If you still have this issue, it's probably for another reason.
