### ISSUE TITLE
Log command fails, 

### ISSUE THREAD

**Issue by JosephGJ** [appcelerator-archive/amp#369]
Log command fails whenever it runs. 

Currently on docker 1.12.2-Beta28. 

When running `amp logs etcd`

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x187ec1]

goroutine 1 [running]:
panic(0x5861c0, 0xc4200120b0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/appcelerator/amp/vendor/google.golang.org/grpc.Invoke(0x8e4f20, 0xc4203805a0, 0x629007, 0xe, 0x5a3700, 0xc4202a3260, 0x5b2a20, 0xc420315880, 0x0, 0x0, ...)
        /Users/jgrahamjones/work/src/github.com/appcelerator/amp/vendor/google.golang.org/grpc/call.go:158 +0x231
github.com/appcelerator/amp/api/rpc/logs.(*logsClient).Get(0xc4200886d8, 0x8e4f20, 0xc4203805a0, 0xc4202a3260, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/jgrahamjones/work/src/github.com/appcelerator/amp/api/rpc/logs/logs.pb.go:118 +0xd2
main.Logs(0xc42033d1e0, 0x9104c0, 0xc42033cb00, 0x1, 0x1, 0xa6b4b, 0x1)
        /Users/jgrahamjones/work/src/github.com/appcelerator/amp/cmd/amp/logs.go:76 +0x604
main.glob..func2(0x9104c0, 0xc42033cb00, 0x1, 0x1)
        /Users/jgrahamjones/work/src/github.com/appcelerator/amp/cmd/amp/logs.go:18 +0x59
github.com/appcelerator/amp/vendor/github.com/spf13/cobra.(*Command).execute(0x9104c0, 0xc42033cac0, 0x1, 0x1, 0x9104c0, 0xc42033cac0)
        /Users/jgrahamjones/work/src/github.com/appcelerator/amp/vendor/github.com/spf13/cobra/command.go:626 +0x443
github.com/appcelerator/amp/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x9106e0, 0xc42026bec8, 0x62935d, 0xe)
        /Users/jgrahamjones/work/src/github.com/appcelerator/amp/vendor/github.com/spf13/cobra/command.go:712 +0x367
github.com/appcelerator/amp/vendor/github.com/spf13/cobra.(*Command).Execute(0x9106e0, 0xc42026bec0, 0x1)
        /Users/jgrahamjones/work/src/github.com/appcelerator/amp/vendor/github.com/spf13/cobra/command.go:671 +0x2b
main.main()
        /Users/jgrahamjones/work/src/github.com/appcelerator/amp/cmd/amp/main.go:79 +0x3b0
```

**Comment by subfuzion** [comment]
Lets make [the red cells turn green](https://docs.google.com/spreadsheets/d/1i_fZ9ArzQwnePRPpudxk69f4_CIYk7WBMX73m1IOifY/edit?usp=sharing)! Rather than waiting for log events to be generated and queued up, it should be possible to explicitly generate data and then confirm that the data is ultimately received by the client within a certain short time threshold.

**Comment by bquenin** [comment]
I didn't manage to reproduce this behavior neither on tag `0.2.0` nor on `master`.

**Comment by ndegory** [comment]
Not able to reproduce either (master, Docker 1.12.2 on Ubuntu).
The log looks like the issue we had last week with the stats command failing once in a while.

**Comment by subfuzion** [comment]
Unfortunately, it's failing for both @JosephGJ and myself. I'm on the stable version of Docker for Mac (1.12.1) and he's on the beta channel version (1.12.2). Joseph was trying to do some test enhancements, but was blocked by the log tests not passing. As long as you are able to work on augmenting the log tests  and other integration tests per #370, then I guess we're ok.

**Comment by bquenin** [comment]
Is it still necessary to keep this issue ?

**Comment by subfuzion** [comment]
Nope!
