### ISSUE TITLE
amp stats crashing on Windows

### ISSUE THREAD

**Issue by neha-viswanathan** [appcelerator-archive/amp#446]
Tested the amp and amplifier binaries on Windows 10. 
Executing `amp stats` command resulted in the following error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0xc0 pc=0x529dfc]

goroutine 67 [running]:
panic(0xb71d20, 0xc0420080a0)
        /usr/local/go/src/runtime/panic.go:500 +0x1af
github.com/appcelerator/amp/api/rpc/stats.StatsReply.Less(0xc042144200, 0xf, 0xf, 0xe, 0x0, 0x0)
        /go/src/github.com/appcelerator/amp/api/rpc/stats/stats.go:452 +0x4c
github.com/appcelerator/amp/api/rpc/stats.(*StatsReply).Less(0xc0421d6f20, 0xe, 0x0, 0x0)
        <autogenerated>:3 +0x7f
sort.medianOfThree(0x105c100, 0xc0421d6f20, 0x0, 0x7, 0xe)
        /usr/local/go/src/sort/sort.go:78 +0x85
sort.doPivot(0x105c100, 0xc0421d6f20, 0x0, 0xf, 0xc042254da0, 0x19)
        /usr/local/go/src/sort/sort.go:103 +0xae
sort.quickSort(0x105c100, 0xc0421d6f20, 0x0, 0xf, 0x7)
        /usr/local/go/src/sort/sort.go:188 +0x8a
sort.Sort(0x105c100, 0xc0421d6f20)
        /usr/local/go/src/sort/sort.go:222 +0x87
github.com/appcelerator/amp/api/rpc/stats.(*Stats).StatsQuery(0xc0423e40a0, 0x105fc40, 0xc0423e2e10, 0xc0423f8120, 0x0, 0x11, 0x11)
        /go/src/github.com/appcelerator/amp/api/rpc/stats/stats.go:68 +0x1a9
github.com/appcelerator/amp/api/rpc/stats._Stats_StatsQuery_Handler(0xc21da0, 0xc0423e40a0, 0x105fc40, 0xc0423e2e10, 0xc0423e4500, 0x0, 0x0, 0x0, 0x108ad40, 0x40e464)
        /go/src/github.com/appcelerator/amp/api/rpc/stats/stats.pb.go:168 +0x284
github.com/appcelerator/amp/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc0423ee0a0, 0x1062480, 0xc0423f03f0, 0xc0423f42d0, 0xc0423e2450, 0x10791c0, 0xc0423e2de0, 0x0, 0x0)
        /go/src/github.com/appcelerator/amp/vendor/google.golang.org/grpc/server.go:611 +0xc1b
github.com/appcelerator/amp/vendor/google.golang.org/grpc.(*Server).handleStream(0xc0423ee0a0, 0x1062480, 0xc0423f03f0, 0xc0423f42d0, 0xc0423e2de0)
        /go/src/github.com/appcelerator/amp/vendor/google.golang.org/grpc/server.go:769 +0x6b7
github.com/appcelerator/amp/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0423e03d0, 0xc0423ee0a0, 0x1062480, 0xc0423f03f0, 0xc0423f42d0)
        /go/src/github.com/appcelerator/amp/vendor/google.golang.org/grpc/server.go:422 +0xb2
created by github.com/appcelerator/amp/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
        /go/src/github.com/appcelerator/amp/vendor/google.golang.org/grpc/server.go:423 +0xaa
```

**Comment by freignat91** [comment]
Should be the case for all about commands considering #447, is-it, or it's specific to stats command?
